In [1]:
import numpy as np

In [2]:
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [5]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [6]:
A = np.random.randn(10)

In [7]:
A

array([-0.80236885,  0.84748407, -0.39339234, -0.4206147 ,  0.2047193 ,
        2.90733066,  1.22487452,  0.23159374, -0.81084168,  0.25295671])

In [8]:
B = np.random.randn(10)

In [9]:
B

array([-1.28779896,  2.89912015, -0.44125516,  1.31387569, -0.56425152,
       -1.85171794,  0.43963481,  0.32617563,  0.09831166, -1.09576723])

In [10]:
np.add(A,B)

array([-2.09016782,  3.74660422, -0.83464751,  0.89326099, -0.35953222,
        1.05561272,  1.66450933,  0.55776937, -0.71253002, -0.84281052])

In [11]:
np.maximum(A,B)

array([-0.80236885,  2.89912015, -0.39339234,  1.31387569,  0.2047193 ,
        2.90733066,  1.22487452,  0.32617563,  0.09831166,  0.25295671])