In [1]:
import numpy as np

In [2]:
arr = np.arange(5)

In [3]:
arr

array([0, 1, 2, 3, 4])

In [4]:
np.save('my_array', arr)

In [5]:
arr = np.arange(10)

In [6]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.load('my_array.npy')

array([0, 1, 2, 3, 4])

In [8]:
arr1 = np.load('my_array.npy')

In [9]:
arr2 = np.arange(10)

In [10]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr1

array([0, 1, 2, 3, 4])

In [12]:
np.savez('ziparray.npz', x=arr1, y=arr2)

In [13]:
archive_array = np.load('ziparray.npz')

In [14]:
archive_array

In [15]:
archive_array['x']

array([0, 1, 2, 3, 4])

In [16]:
arr = np.array([[1,2,3,4], [4,5,6,7]])

In [17]:
arr

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [18]:
np.savetxt('my_test_text.txt', arr, delimiter=',')

In [19]:
!cat my_test_text.txt

1.000000000000000000e+00,2.000000000000000000e+00,3.000000000000000000e+00,4.000000000000000000e+00
4.000000000000000000e+00,5.000000000000000000e+00,6.000000000000000000e+00,7.000000000000000000e+00


In [20]:
arr = np.loadtxt('my_test_text.txt', delimiter=',')

In [21]:
arr

array([[1., 2., 3., 4.],
       [4., 5., 6., 7.]])