In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
arr1 = np.arange(9).reshape((3,3))

In [3]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [5]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
ser1 = Series([0,1,2], index=['T','U','V'])
ser2 = Series([3,4], index=['X','Y'])

In [9]:
ser1

T    0
U    1
V    2
dtype: int64

In [10]:
ser2

X    3
Y    4
dtype: int64

In [11]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [12]:
pd.concat([ser1,ser2,ser1])

T    0
U    1
V    2
X    3
Y    4
T    0
U    1
V    2
dtype: int64

In [15]:
pd.concat([ser1,ser2], axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [16]:
pd.concat([ser1,ser2], keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [18]:
pd.concat([ser1,ser2], axis=1, keys=['cat1','cat2'])

cat1  cat2
T   0.0   NaN
U   1.0   NaN
V   2.0   NaN
X   NaN   3.0
Y   NaN   4.0

In [19]:
dframe1 = DataFrame(np.random.randn(4,3), columns=['X','Y','Z'])

In [20]:
dframe1

X         Y         Z
0 -1.577115  1.586888 -0.064319
1 -0.489321  1.366616  0.011961
2 -1.427436 -0.138861  1.183390
3 -1.157139  1.043096  0.089153

In [21]:
dframe2 = DataFrame(np.random.randn(3,3), columns=['Y','Q','X'])

In [22]:
dframe2

Y         Q         X
0 -1.368755  0.133903  1.754501
1  0.403280  1.057155 -2.815269
2 -0.125826 -1.654151 -0.481875

In [23]:
pd.concat([dframe1, dframe2])

X         Y         Z         Q
0 -1.577115  1.586888 -0.064319       NaN
1 -0.489321  1.366616  0.011961       NaN
2 -1.427436 -0.138861  1.183390       NaN
3 -1.157139  1.043096  0.089153       NaN
0  1.754501 -1.368755       NaN  0.133903
1 -2.815269  0.403280       NaN  1.057155
2 -0.481875 -0.125826       NaN -1.654151

In [24]:
pd.concat([dframe1, dframe2], ignore_index=True)

X         Y         Z         Q
0 -1.577115  1.586888 -0.064319       NaN
1 -0.489321  1.366616  0.011961       NaN
2 -1.427436 -0.138861  1.183390       NaN
3 -1.157139  1.043096  0.089153       NaN
4  1.754501 -1.368755       NaN  0.133903
5 -2.815269  0.403280       NaN  1.057155
6 -0.481875 -0.125826       NaN -1.654151